import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react';
import Router, { withRouter } from 'next/router'
import axios from 'axios';
import { MainContainer, LoginButton, CadastroButton, ErrorMsg, Form } from '../styles/Styled'
let localAPI = process.env.localAPI
//let remoteAPI= "https://trabseg-api.herokuapp.com"
console.log(localAPI);

export default function Home() {

  const [dadosIncorretos, setDadosIncorretos] = useState(false)
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [token, setToken] = useState("")

  useEffect(() => {
    let temp = localStorage.getItem("accesstoken")

    if (temp) {
      setToken(temp)
      Router.push({ pathname: '/dashboard' })
    } else {
      //nao tem token
    }

  }, [])

  const handleSubmit = (evt) => {
    evt.preventDefault();

    if (email !== "" && password !== "") {
      axios.post(`${localAPI}/auth/login`, {
        email: email,
        password: password
      })
        .then(function (response) {
          localStorage.setItem('accesstoken', response.data.accesstoken)
          Router.push({ pathname: '/dashboard' })
        }).catch(function (error) {
          console.log("Erro: " + error);
          setDadosIncorretos(true)
        })
    } else {
      console.log("Email ou senha vazios");
      setDadosIncorretos(true)
    }

  }

  return (

    <MainContainer>
      <Head>
        <title>Trabalho 2 - Segurança em Sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Trabalho de Segurança em Sistemas</p>
        <p>ToDo App</p>
        <Form onSubmit={handleSubmit}>
          
          <label>
          
          E-mail :<input
              type="email"
              value={email}
              placeholder="Insira seu e-mail"
              onChange={e => setEmail(e.target.value)}
            />
          </label>
          
          <label>
          Senha :<input
              type="password"
              value={password}
              placeholder="Insira sua senha"
              onChange={e => setPassword(e.target.value)}
            />
          </label>
          <span>
            <input type="submit" value="Login" />
            <button onClick={() => Router.push({ pathname: '/cadastro' })}>Criar conta</button>
          </span>


          {dadosIncorretos ? <ErrorMsg> Dados incorretos </ErrorMsg> : null}
        </Form>
      </main>





    </MainContainer>
  )
}
