import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react';
import Router, { withRouter } from 'next/router'
import axios from 'axios';

export default function Home() {

  const [dadosIncorretos, setDadosIncorretos] = useState(false)
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [token, setToken] = useState("")

  useEffect(() => {
    let temp = localStorage.getItem("accesstoken")

    if (temp) {
      setToken(temp)
      Router.push({ pathname: '/dashboard' })
    } else {
      //nao tem token
    }

  }, [])

  const handleSubmit = (evt) => {
    evt.preventDefault();

    axios.post("http://localhost:3333/auth/login", {
      email: email,
      password: password
    })
      .then(function (response) {
        localStorage.setItem('accesstoken', response.data.accesstoken)
        Router.push({ pathname: '/dashboard' })
      }).catch(function (error) {
        console.log("Erro: " + error);
        setDadosIncorretos(true)
      })


  }

  return (

    <div>
      <Head>
        <title>Trabalho 2 - Segurança em Sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={handleSubmit}>
          <label>
            E-mail:
            <input
              type="email"
              value={email}
              onChange={e => setEmail(e.target.value)}
            />
          </label>
          <label>
            Senha:
            <input
              type="password"
              value={password}
              onChange={e => setPassword(e.target.value)}
            />
          </label>
          <input type="submit" value="Login" />
        </form>
      </main>

      {dadosIncorretos ? <div> Dados incorretos </div> : null}

      <button onClick={() => Router.push({ pathname: '/cadastro' })}>Criar usuário</button>

      <footer>
        By Rodrigo de Brito
      </footer>
    </div>
  )
}
